version: "3"
services:
  postgres_notification:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      notification_db:
        ipv4_address: ${DB_HOST}

  postgres_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres_notification
    networks:
      notification_db:
        ipv4_address: 172.19.0.13
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass

networks:
  notification_db:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1